apiVersion: v2
type: application
name: otel-prometheus-grafana
version: 0.0.1
description: opentelemetry demo helm chart with prometheus and grafana
home: https://opentelemetry.io/
sources:
  - https://github.com/isc-srajagop/otel-prometheus-grafana
maintainers:
  - name: isc-srajagop
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: "1.7.0"
dependencies:
  - name: opentelemetry-collector
    version: 0.78.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
  - name: jaeger
    version: 0.73.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: prometheus
    version: 25.8.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.2.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
